/* eslint-disable max-len */
/* eslint-disable no-useless-escape */
/* eslint-disable max-lines */
let profList = [
  "\\bairhead",
  "\\barse\\b",
  "\\bass\\b",
  "\\bbastard",
  "\\bbimbo",
  "\\bbitch",
  "\\bbonehead",
  "\\bclit",
  "\\bcock\\b",
  "\\bcum\\b",
  "\\bcunt",
  "\\bdick\\b",
  "\\bdouche",
  "\\bfag",
  "\\bfuck",
  "\\bkunt",
  "\\bmotherfuck",
  "\\bnigga",
  "\\bnigger",
  "\\bperver",
  "\\bpiss",
  "\\bpoo\\b",
  "\\bporn",
  "\\bprick",
  "\\bpussi",
  "\\bpussy",
  "\\bretard",
  "\\bscum",
  "\\bshit",
  "\\bslut",
  "you tard",
  "\\btit\\b",
  "\\btwat",
  "\\bwack off",
  "\\bwhore",
  "blowjob",
  "bog off",
  "bollocks",
  "boner",
  "bugger",
  "bullshit",
  "\\bcrap",
  "damn",
  "dildo",
  "dipshit",
  "dope",
  "fat ass",
  "fatass",
  "fucker\\b",
  "hooker",
  "horny",
  "jackass",
  "jerk",
  "jizz",
  "jungle bunny",
  "junglebunny",
  "minger",
  "nutsack",
  "pain in the ass",
  "piece of shit",
  "piss off",
  "puke",
  "sand nigger",
  "sandnigger",
  "schmuck",
  "screw up",
  "shmuck",
  "skank",
  "slag",
  "smart-arse",
  "smart\\-ass",
  "son of a bitch",
  "suckass",
  "sucker",
  "sucker\\b",
  "tight-arse",
  "tight-ass",
  "tosser",
  "\\bextremetech\\\\.com\\b",
  "\\bchacha\\\\.com\\b",
  "\\bfreemathhelp\\\\.com\\b",
  "\\bwebmath\\.com\\b",
  "\\bmathway\\\\.com\\b",
  "\\bbbc\\\\.co\\\\.uk\\b",
  "\\bm\\\\.theartstory\\\\.org\\b",
  "\\bwiki\\\\.answers\\\\.com\\b",
  "\\bhealthyheart\\\\.nhs\\\\.uk\\b",
  "\\bthefreedictionary\\\\.com\\b",
  "\\bpbs\\\\.org\\b",
  "\\btricksmate\\\\.com\\b",
  "\\bonlinestatbook\\\\.com\\b",
  "\\ben\\\\.wikipedia\\\\.org\\b",
  "\\breal\\-world\\-physics\\-problems\\\\.com\\b",
  "\\blordsandladies\\\\.org\\b",
  "\\bclickandlearn\\\\.cc\\b",
  "\\bwebpages\\\\.uidaho\\\\.edu\\b",
  "\\baryasamaj\\\\.com\\b",
  "\\bvark\\-learn\\\\.com\\b",
  "\\blinux\\\\.about\\\\.com\\b",
  "\\breadwritethink\\\\.org\\b",
  "\\bsparknotes\\\\.com\\b",
  "\\balphabetize\\\\.org\\b",
  "\\bpenpals\\\\.web\\\\.unc\\\\.edu\\b",
  "\\btranslate\\\\.google\\\\.ca\\b",
  "\\bt\\\\.answers\\\\.com\\b",
  "\\bdictionary\\\\.reference\\\\.com\\b",
  "\\brhythm-india\\\\.com\\b",
  "\\bmintaka\\\\.sdsu\\\\.edu\\b",
  "\\bnationalgeographic\\\\.com\\b",
  "\\bmathsisfun\\\\.com\\b",
  "\\bedublogs\\\\.org\\b",
  "\\bblogspot\\\\.com\\b",
  "\\balgebra\\\\.com\\b",
  "\\bdelaware\\\\.gov\\b",
  "\\beasybib\\\\.com\\b",
  "\\bpullman\\\\.co\\\\.uk\\b",
  "\\bthenest\\\\.com\\b",
  "\\bbuyessays\\\\.us\\b",
  "\\btqn\\\\.com\\b",
  "titanpad",
  "titanpad\\\\.com",
  "www\\\\.titanpad\\\\.com",
  "\\bc0ck",
  "\\bh\\@andjob",
  "\\bhandj0b",
  "\\bh\\@andj0b",
  "\\bfück",
  "\\bfûck",
  "\\bfúck",
  "fúck\\b",
  "fûck\\b",
  "fück\\b",
  "sexy",
  "fu\\\\.ck",
  "puss\\.y",
  "fuc\\\\.k",
  "f\\\\.uck",
  "p\\\\.ussy",
  "pu\\\\.ssy",
  "pus\\\\.sy",
  "f\\\\.u\\\\.c\\\\.k",
  "p\\\\.u\\\\.s\\\\.s\\\\.y",
  "\\\\.jpg",
  "send nudes",
  "mothafucka",
  "\\bboob",
  "\\bsslut\\b",
  "\\bniqqa",
  "\\bazz\\b",
  "\\blmao\\b",
  "\\bfuk",
  "\\bbich\\b",
  "\\bbiach\\b",
  "\\bdumass\\b",
  "\\bkys\\b",
  "\\bstfu\\b",
  "\\bfuqq\\b",
  "\\bfuq\\b",
  "\\bcrip\\b",
  "\\bdikk\\b",
  "b\\\\.i\\\\.t\\\\.c\\\\.h",
  "\\bwtf\\b",
  "nigg3r",
  "niggur",
  "\\bhoe\\b",
  "\\bh0e\\b",
  "fricken",
  "\\basf\\b",
  "\\bpusy",
  "cumming",
  "\\bcum\\b",
  "faggt",
  "\\bas f*$\\b",
  "b\\*tch",
  "\\bf u c k",
  "\\bb i t c h",
  "n!gg3r",
  "\\bsl ut\\b",
  "\\bdumb4zz",
  "\\bidfc",
  "\\blmfao",
  "\\bniga",
  "\\bw hore",
  "\\bb\\\\.tch\\b",
  "\\bd i c k\\b",
  "\\bfboy\\b",
  "\\bfgirl\\b",
  "\\bb1tch\\b",
  "\\bfck\\b",
  "\\bf\\.u\\.c\\.k\\b",
  "\\bfu\\*\\*\\b",
  "\\bho\\*\\b",
  "\\bho\\b",
  "\\bbeyotch",
  "\\bbiatch",
  "fukboi",
  "\\b4ss\\b",
  "\\bdouche",
  "wwhore",
  "\\br e t a r d\\b",
  "\\bf\\=\\=k",
  "butthurt",
  "\\bf off\\b",
  "\\bdicc",
  "\\blick you\\b",
  "\\bf a g g e t\\b",
  "\\bfagget\\b",
  "\\bd!ck",
  "\\bn\\!gger",
  "buttsex",
  "\\bwh ore\\b",
  "\\bsl ut\\b",
  "\\bbish\\b",
  "\\bthot\\b",
  "\\bfuc k\\b",
  "\\ba s s\\b",
  "\\bc\\\\.unt",
  "\\bc u n t",
  "\\bbit ch",
  "\\bfack",
  "\\bfu\\#ck\\b",
  "\\bsh it\\b",
  "\\bcr\\!p",
  "\\bh orny\\b",
  "\\bnicca\\b",
  "\\bfukk\\b",
  "\\bn\\!gg",
  "\\bnig ga\\b",
  "\\bpedo\\b",
  "pedophile",
  "molest",
  "\\bf\\#\\#k\\b",
  "mathway",
  "\\bsmd\\b",
  "\\bb\\!tch",
  "fuck\\b",
  "nlgger",
  "\\ba55",
  "\\bbxtches",
  "\\bnude",
  "fuuck",
  "nigg",
  "\\ba\\\\*\\\\*hole",
  "asshole",
  "give me head",
  "naked photos",
  "a queer",
  "fucKed",
  "fuvk",
  "bitc\\*",
  "dezz nuts",
  "d e e z n u t s",
  "\\bcu m",
  "bihh",
  "f\\*ck",
  "f\\*k",
  "f\\*\\*k",
  "c\\*unt",
  "c\\*\\*\\*",
  "c\\*\\*t",
  "sh\\*t",
  "f\\-uck",
  "female dog",
  "blowjob",
  "f\\*\\*\\*\\*\\*\\*",
  "f\\*\\*\\*\\*\\*g",
  "f\\*\\*\\*ing",
  "d\\*\\*\\*",
  "dick",
  "shit",
  "your butt",
  "j\\\\.erk",
  "f a g g e t",
  "f a g g o t",
  "fagget",
  "my penis",
  "smd",
  "bdsm",
  "kick your ass",
  "have s e x",
  "f u c k",
  "\\bsthu\\b",
  "\\bcuum",
  "c\\\\.u\\\\.n\\\\.t",
  "f\\-u\\-c\\-k",
  "drink bleach",
  "\\bpuss\\b",
  "kill yourself",
  "\\bk y s",
  "negger",
  "n\\\\.igg",
  "n i g g",
  "niqq",
  "biitch",
  "s\\\\.hit",
  "cu\\.nt",
  "\\bpedo\\b",
  "\\bpaedo",
  "f\\.uck",
  "a\\.\\.ss",
  "http://zzz\\.totmania\\.net",
  "\\bhoee",
  "fvck",
  "dickhead",
  "dick head",
  "\\bnigg",
  "blow job",
  "nagger",
  "shiz",
  "motherflutter",
  "\\bfuc\\b",
  "motherfuc",
  "t i t t i e s",
  "t i t t y",
  "b\\.i\\.t\\.c\\.h",
  "bi tch",
  "f/uck",
  "fu/ck",
  "fuc/k",
  "d/ick",
  "di/ck",
  "dic/k",
  "s/hit",
  "sh/it",
  "shi/t",
  "tiddy",
  "t1tt",
  "my balls",
  "your balls",
  "my penis",
  "your penis",
  "f\\.\\.uck",
  "\\bfucc",
  "btch",
  "f’uck",
  "f’ag",
  "@ss",
  "faygit",
  "hentai",
  "henta1",
  "suck cok",
  "my cok",
  "n!gg",
  "\\brape\\b",
  "screw you",
  "sex with me",
  "\\blick my",
  "\\blick you",
  "my dong",
  "google hangout",
  "pu$y",
  "pu$",
  "pusy",
  "a\\$\\$",
  "\\bhoes\\b",
  "h0e",
  "ƒuck",
  "niqa",
  "$hit",
  "\\bfxx",
  "w\\.t\\.f",
  "but hole",
  "cvnt",
  "f,ck",
  "f\\*ck",
  "w\\.h\\.o\\.r\\.e",
  "batshit",
  "\\bdik",
  "vegina",
  "my dick",
  "your dick",
  "ur dick",
  "\\brapist",
  "twat",
  "tw@t",
  "my vagina",
  "your vagina",
  "your puss",
  "my puss",
  "pu55y",
  "friggin",
  "thong",
  "#ERROR!",
  "\\bsucc\\b",
  "stripper",
  "dushbag",
  "midget",
  "fcuk",
  "\\bfck",
  "bicth",
  "p/ussy",
  "pu/ssy",
  "pus/sy",
  "puss/y",
  "pu$",
  "your snatch",
  "ur snatch",
  "her snatch",
  "her vagina",
  "his dick",
  "https://yadi\\.sk/",
  "\\bputa\\b",
  "\\bvag\\b",
  "\\bmath way",
  "nigga",
  "fucking",
  "fuck",
  "beat meat",
  "beat my meat",
  "beat his meat",
  "cummies",
  "\\baf\\b",
  "shoot illegal",
  "kill ni",
  "kill illegal",
  "\\banal\\b",
  "tallywacker",
  "Fuck",
  "Cunt",
  "Bitch",
  "Shit",
  "Nigg",
  "Fag",
  "nuds",
  "fuc\\*",
  "drink some bleach",
  "drink bleach",
  "fuuck",
  "\\bspic\\b",
  "Puss\\b",
  "sl-ut",
  "f-uck",
  "f\\*\\*k",
  "\\bf you\\b",
  "\\bf that\\b",
  "f$ck",
  "finger me",
  "finger you",
  "finger her",
  "pen1s",
  "fиck",
  "suck my",
  "fml",
  "deez nuts",
  "deez nutz",
  "my nuts",
  "n!99",
  "sh!t",
  "n199",
  "n1gg",
  "ni99",
  "\\bsht\\b",
  "my ig",
  "ig @",
  "my snap",
  "snap @",
  "insta @",
  "instagram @",
  "math way",
  "weiner",
  "pwussy",
  "your pushy",
  "puthy",
  "suck me",
  "suck my",
  "\\bTITS\\b",
  "\\bscrew u\\b",
  "ɴɪɢɢᴇʀ",
  "dyke",
  "dipsh\\*\\*",
  "dumbass",
  "\\bsh\\*\\*",
  "f-u-k",
  "\\bnig\\b",
  "bichth",
  "\\bigger\\b",
  "1gger",
  "peeranswer",
  "nibba",
  "b!tch",
  "\\bcunt",
  "soundcloud",
  "snapchat",
  "black lives don't matter",
  "redpill",
  "@gmail",
  "@yahoo",
  "@outlook",
  "nigger",
  "ᴘᴜssʏ",
  "ᴀss",
  "ʙɪᴛᴄʜ",
  "sɴɪᴛᴄʜ",
  "ᴛʜᴏᴛ",
  "ғᴜᴄᴋɪɴɢ",
  "ғ",
  "biotch",
  "\\bcock\\b",
  "\\bcocks\\b",
  "bit\\.ly",
  "\\ba tard\\b",
  "ujeb\\.se",
  "bit\\.do",
  "bööb",
  "hyperurl\\.co",
  "possy",
  "A > S > S",
  "A < S < S",
  "\\bdiscord\\.gg",
  "smartass",
  "fuxk",
  "booty",
  "lmao",
  "lmaoo",
  "fxck",
  "\\bkys\\b",
  "\\bkms\\b",
  "\\bkill yourself\\b",
  "\\bkill myself\\b",
  "omfg",
  "axxhole",
  "p0rn",
  "0rgy",
  "fvck",
  "tbfh",
  "facebook",
  "gmail",
  "Odysseyware",
  "titts",
  "大",
  "\\bLive\\b2018",
  "办美",
  "405665716",
  "319777586",
  "860801713",
  "707091118",
  "blogspot",
  "liveonhd",
  "deadass",
  "blyat",
  "fuck",
  "\\.jpg",
  "\\.png",
  "vstvon",
  "\\.de",
  "wimbledonpc",
  "Live®",
  "francevs",
  "supplierbin",
  "livegfootball",
  "funckin",
  "tourfrancede",
  "liveifootball",
  "supplierbin",
  "britishopen",
  "\\.icu",
  "livetowatch",
  "lionsvs",
  "youtube",
  "youtube\\.om",
  "\\brape\\b",
  "https://www\\.greatlovespells\\.co\\.uk",
  "greatlovespells",
  "whatsapp",
  "Watch WWE Smackdown",
  "mazda-ottawa",
  "\\.ncwit\\.",
  "buddypress\\.org",
  "\\.richlandsource\\.",
  "kansas-vs-michigan",
  "\\.okdrs\\.",
  "opengameart\\.org",
  "thephillyegotist\\.",
  "thewellproject\\.",
  "-vs-",
  "\\.reddit\\.",
  "\\.eu/",
  "live-",
  "/files/",
  "watch-",
  "-vs-",
  "grey-cuplive",
  "archiveofourown\\.org",
  "opengameart",
  "watch-",
  "-full-",
  "reddit\\.",
  "DTF",
  "\\btf\\b",
  "f\\*\\*\\*",
  "\\bGTH\\b",
  "w\\.tf",
  "w\\.th",
  "wt_f",
  "vagona",
  "bi\\.tch",
  "cra\\.p",
  "s\\.hit",
  "inanphuquy",
  "tockify\\.com",
  "Best SEO Solutions",
  "suicide",
  "qiita",
  "naughtyboy",
  "pofsex\\.com",
  "pofsex",
  "pofsex\\.com",
  "meetpof",
  "vibrator",
  "badoo",
  "xxvideo\\.com",
  "xxvideo",
  "Xhamster\\.com",
  "https://linktr\\.ee/",
  "julia\\.karandina",
  "https://linktr\\.ee/julia\\.karandina",
  "my username julia_sweety",
  "https://telegra\\.ph/Julia-Sweety-02-21",
  "/Julia-Sweety-02-21",
  "Julia-Sweety-",
  "https://telegra\\.ph/",
  "https://telegra\\.ph",
  "telegra\\.ph",
  "https://linktr\\.ee/-",
  "https://linktr\\.ee/-denis1704",
  "https://linktr\\.ee/-danis1704",
  "danis1704",
  "denis1704",
  "danis",
  "https://telegra\\.ph/",
  "my username danis1704_danis1704",
  "my username_ danis1704",
  "@",
  "h\\.e\\.l\\.l\\.",
  "covid",
  "tiktok",
  "tik tok",
  "Tik Tok",
  "'''customer \"\"\"\"\"",
  "'''",
  "'''c \"\"\"\"\"",
  "Kartvally",
  "Mojofox",
  "Dailyknots",
  "\\.\\.\\.customer\\.\\.\\.",
  "Mozpassport\\.com",
  "MOZ",
  "meet\\.google\\.com",
  "meet\\.google",
  "padlet\\.com",
  "zoom\\.us",
  "docs\\.google\\.com",
  "google\\.com",
  "docs\\.google",
  "Edgenuity",
  "Apex",
  "edgenuity",
  "apex",
  "roblox",
  "https://consumer\\.klickly\\.com",
  "klickly\\.com",
  "klickly",
  "https://consumer\\.klickly",
  "https://consumer\\.klickly",
  "chatt-sex\\.online",
  "sexx-chat\\.site",
  "sexxx-chat\\.site",
  "MASTERBATE",
  "sex-today\\.fun",
  "sexx-today\\.fun",
  "sexxx-today\\.fun",
  "MASTERBATION",
  "sex-chat",
  "sexx-chat",
  "sexxx-chat",
  "sex-partners\\.biz",
  "sex-partners",
  "sexxx-partners\\.biz",
  "sexx-partners\\.biz",
  "partners\\.biz",
  "sexyphotos\\.online",
  "gimkit\\.com",
  "GIMKIT",
  "po!rn",
  "Po!rn",
  "P0rn",
  "porn",
  "ROBLOX",
  "roblox",
  "instagram",
  "Instagram",
  "masterbate",
  "h0rney",
  "h0rny",
  "Google",
  "google",
  "skype",
  "HOMOPHOBIC",
  "homo",
  "homophobic",
  "N I G G E R",
  "chatt - sex\\.online",
  "chatt-sex\\.online",
  "sex\\.online",
  "chat-sex\\.online",
  "chattt - sex\\.online",
  "cuteladies\\.xyz",
  "WEBCAM",
  "WEB!CAM",
  "MAST!URB!ATE",
  "brainlygirls",
  "girls\\.online",
  "\\.online",
  "nu!de",
  "ba!be",
  "brainly\\.today",
  "NUD!E",
  "girlfriend",
  "boyfriend",
  "Hinge",
  "Tinder",
  "s e x",
  "chat",
  "dumb",
  "hacked",
  "stupid",
  "google",
  "damn",
  "sexy",
  "B R A I N LY\\. T O D A Y",
  "ʙʀᴀɪɴʟʏ\\.ᴛᴏᴅᴀʏ",
  "BRAINLY\\.TODAY",
  "Padlet",
  "padlet",
  "sexdates\\.fun",
  "www\\.sexdates\\.fun",
  "Fu*k me",
  "Fu*k",
  "fu*k",
  "www\\.caffeine\\.tv/Cheerqueenslove/broadcast",
  "www\\.caffeine\\.tv",
  "www\\.caffeine\\.tv/",
  "caffeine\\.tv",
  "caffeine\\.tv/",
  "youtubr",
  "TIK TOKS",
  "①|②|③|④|⑤|⑥|⑦|⑧|⑨|⑩|⑪|⑫|⑬|⑭|⑮|⑯|⑰|⑱|⑲|⑳|⑴|⑵|⑶|⑷|⑸|⑹|⑺|⑻|⑼|⑽|⑾|⑿|⒀|⒁|⒂|⒃|⒄|⒅|⒆|⒇|⒈|⒉|⒊|⒋|⒌|⒍|⒎|⒏|⒐|⒑|⒒|⒓|⒔|⒕|⒖|⒗|⒘|⒙|⒚|⒛|⒜|⒝|⒞|⒟|⒠|⒡|⒢|⒣|⒤|⒥|⒦|⒧|⒨|⒩|⒪|⒫|⒬|⒭|⒮|⒯|⒰|⒱|⒲|⒳|⒴|⒵|Ⓐ|Ⓑ|Ⓒ|Ⓓ|Ⓔ|Ⓕ|Ⓖ|Ⓗ|Ⓘ|Ⓙ|Ⓚ|Ⓛ|Ⓜ|Ⓝ|Ⓞ|Ⓟ|Ⓠ|Ⓡ|Ⓢ|Ⓣ|Ⓤ|Ⓥ|Ⓦ|Ⓧ|Ⓨ|Ⓩ|ⓐ|ⓑ|ⓒ|ⓓ|ⓔ|ⓕ|ⓖ|ⓗ|ⓘ|ⓙ|ⓚ|ⓛ|ⓜ|ⓝ|ⓞ|ⓟ",
  "ⓠ|ⓡ|ⓢ|ⓣ|ⓤ|ⓥ|ⓦ|ⓧ|ⓨ|ⓩ|⓪|⓫|⓬|⓭|⓮|⓯|⓰|⓱|⓲|⓳|⓴|⓵|⓶|⓷|⓸|⓹|⓺|⓻|⓼|⓽|⓾|⓿|㊲|㊳|㊴|㊵|㊶|㊷|㊸|㊹|㊺|㊻|㊼|㊽|㊾|㊿|㏠|㏡|㏢|㏣|㏤|㏥|㏦|㏧|㏨|㏩|㏪|㏫|㏬|㏭|㏮|㏯|㏰|㏱|㏲|㏳|㏴|㏵|㏶|㏷|㏸|㏹|㏺|㍘|㍙|㍚|㍛|㍜|㍝|㍞|㍟|㍠|㍡|㍢|㍣|㍤|㍥|㍦|㍧|㍨|㍩|㍪|㍫|㍬|㍭|㍮|㍯|㍰|０|１|２|３|４|５|６|７|８|９|Ａ|Ｂ|Ｃ|Ｄ|Ｅ|Ｆ|Ｇ|Ｈ|Ｉ|Ｊ|Ｋ|Ｌ|Ｍ|Ｎ|Ｏ|Ｐ|Ｑ|Ｒ|Ｓ|Ｔ",
  "Ｕ|Ｖ|Ｗ|Ｘ|Ｙ|Ｚ",
  "p\\*ssy",
  "p\\*ssy now",
  "www\\.sexnow\\.fun",
  "sexnow",
  "b00ty",
  "IDK",
  "idk",
  "bruh",
  "b00bies",
  "boobies",
  "desmos\\.com",
  "p-u-s-s-y",
  "sëx cha\\.t",
  "sex chàt",
  "meetgooglecom/",
  "meetgooglecom",
  "nitrotype\\.com",
  "join my zoom",
  "have zoom",
  "join zoom",
  "make a zoom",
  "open a zoom",
  "on zoom",
  "wanna zoom",
  "zoom code",
  "zoom me",
  "any girls wanna",
  "zoom call",
  "got a zoom",
  "want to zoom",
  "zoom app",
  "join to zoom",
  "join my zoom",
  "my zoom",
  "talk on zoom",
  "zoom meeting",
  "my zoòm",
  "start a zoom",
  "Zoom?",
  "down to zoom",
  "zoomm with",
  "in zoom",
  "zoom join",
  "google meet",
  "\\brate me\\b",
  "watchparty\\.me",
  "follow my insta",
  "shut up",
  "bi\\.t\\.ch",
  "sh\\.i\\.t",
  "cutt\\.ly",
  "herecutt\\.ly",
  "is\\.gd",
  "cutt\\. ly",
  "dogmovie\\.net",
  "tinyurl\\.com",
  "linkcutter\\.ga",
  "yourlink\\.gg",
  "yourlink\\.gq/gyko",
  "shortlnk\\.ml",
  "cutlnk\\.ml",
  "tinylnk\\.ml",
  "shortlnk\\.gq",
  "tinylnk\\.gq",
  "pad\\.let",
  "heretnylnk\\.ml",
  "filetnylnk\\.ml",
  "belowtnylnk\\.ml",
  "tinylnk\\.cf",
  "tinyclick",
  "I can only upload it to a file hosting service",
  "you can download answer here",
  "answer is in a file",
  "customer care number",
  "i hate u",
  "b\\.o\\.o\\.b\\.s",
  "p\\.adlet",
  "pa\\.dlet",
  "pad\\.let",
  "padle\\.t",
  "zooom",
  "quizizz",
  "mathway",
  "math papa",
  "bеlow!xtiny\\.cf",
  "sub to my",
  "yt channel",
  "follow me on insta",
  "add me on snap",
  "hot girls only",
  "im bored",
  "who wanna talk",
  "this isnt a school question",
  "friend zone",
  "horny",
  "Brainly mods",
  "anyone want to be my friend",
  "anyone want to be friends",
  "hunterxhunter",
  "wanna be friends",
  "who has discord",
  "zo\\.om",
  "zo-om",
  "kahoot",
  "what's your favorite",
  "finish the lyric",
  "finish the song",
  "filеxtiny",
  "xtiny",
  "Herе's link tо thе аnswer",
  "Еxplаnаtiоn is in а filе",
  "BlTCH",
  "I uрlоаdеd thе аnswеr tо а filе hоsting",
  "Yоu cаn dоwnlоаd thе аnswеr hеrе",
  "Аnswеr is in а phоtо\\. I cаn оnly uplоаd it to a file hоsting sеrvice",
  "\\.tk",
  "\\.ga",
  "\\.cf",
  "\\.gq",
  "uplоаdеd it tо а filе hоsting",
  "quizlet\\.com",
  "4 sex",
  "zôom",
  "only girls zoom",
  "girls sex",
  "I don't know bro",
  "Herе's link tо thе аnswer",
  "Yоu cаn dоwnlоаd thе аnswеr",
  "girl sex",
  "I cоuldn't аttасh it hеrе, but I uplоаdеd it tо а filе hоsting\\.",
  "do a rp",
  "rp with me",
  "furry rp",
  "anime rp",
  "your fave",
  "just text me",
  "here's my number",
  "here's my email",
  "I do not know the answer to this question",
  "asdfghjkl",
  "bit\\․ly",
  "I uploadеd the answеr tо a filе hosting\\.",
  "for Interested girls",
  "zoo M id",
  "my insta is",
  "i am bored",
  "FREE POINTS",
  "cashapp",
  "cash app",
  "paypal",
  "im gay",
  "i'm gay",
  "bts stan",
  "who wants to talk",
  "p0rn",
  "pad/let",
  "cutt\\․ly",
  "Еxplаnаtiоn is in a filе",
  "rebrandly",
  "tinyurl",
  "bl\\.ink",
  "semrush",
  "ahrefs",
  "sniply",
  "parse\\.ly",
  "su\\.pr",
  "goo\\.gl",
  "is\\.gd",
  "snipurl",
  "tiny\\.cc",
  "fur\\.ly",
  "F R E E P O I N T S",
  "basesfile\\.com",
  "robux",
  "fortnite",
  "minecraft",
  "tik tok",
  "roblox",
  "im bored",
  "name this song",
  "i'm bored",
  "NIGGA",
  "who do you simp for",
  "are you a simp",
  "i'm not a simp",
  "im not a simp",
  "smash or pass",
  "rate me 1",
  "The answer and explanation to your question in a file",
  "anyone wanna talk",
  "anyone wanna rp",
  "tnylnk",
  "cutlnk",
  "who wants to be friends",
  "se x y g i r l s",
  "come have f u n",
  "j oin f as t​",
  "customer /care/ number/",
  "\\*customer\\*care\\* number\\*",
  "shorturl",
  "deeznuts",
  "deez nuts",
  "deeznutz",
  "deez nutz",
  "E⁣xplanation i⁣s i⁣n a f⁣ile",
  "[tex]bit\\.^{}ly",
  "[tex]cutt\\.^{}ly",
  "\\.^{}tk",
  "\\.^{}ga",
  "\\.^{}cf",
  "\\.^{}gq",
  "[tex]basesfiles\\.^{}",
  "[tex]tnylnk\\.^{}",
  "[tex]cutlnk\\.^{}",
  "❤​",
  "u\\.to/",
  "I u⁣⁣ploaded t⁣⁣he a⁣⁣nswer t⁣⁣o a f⁣⁣ile h⁣⁣osting\\.",
  "\\\\.(\\[tex\\]\\.*\\[\tex\\])*l(\\[tex\\]\\.*\\[\tex\\])*y",
  "\\\\.(\\[tex\\]\\.*\\[\tex\\])*t(\\[tex\\]\\.*\\[\tex\\])*k",
  "\\\\.(\\[tex\\]\\.*\\[\tex\\])*c(\\[tex\\]\\.*\\[\tex\\])*f",
  "\\\\.(\\[tex\\]\\.*\\[\tex\\])*m(\\[tex\\]\\.*\\[\tex\\])*l",
  "\\\\.(\\[tex\\]\\.*\\[\tex\\])*g(\\[tex\\]\\.*\\[\tex\\])*a",
  "\\\\.(\\[tex\\]\\.*\\[\tex\\])*g(\\[tex\\]\\.*\\[\tex\\])*q",
  "fûçk",
  "fûçkèr",
  "dîçk",
  "fūčķěř",
  "u⁣⁣⁣ploaded i⁣⁣⁣t t⁣⁣⁣o a f⁣⁣⁣ile h⁣⁣⁣osting",
  "bit\\.[tex]^{}[/tex]ly/3a8Nt8n",
  "shorturl\\.at",
  "xtiny\\.cf",
  "tinylnk\\.cf",
  "tnylnk\\.gq",
  "fu\\.cking",
  "xbox",
  "gamertag",
  "3a8Nt8n",
  "in a filebit",
  "I uploaded it to a file hosting",
  "Answer is in a photo",
  "3tZxaCQ",
  "bit\\.[tex]^{}[/tex]ly/3tZxaCQ",
  "bit\\.[tex]^{}[/tex]ly",
  "Explanation is[tex]^{}[/tex] in a file",
  "You can download[tex]^{}[/tex] the answer",
  "I can only upload[tex]^{}[/tex] it to a file",
  "file hosting service\\. link",
  "Here's link[tex]^{}[/tex]",
  "photomath",
  "bad bvtch",
  "NlGGA",
  "2f3T96",
  "Answer:heyExplanation:",
  "Answer:hiExplanation:",
  "H⁣ere's li⁣nk t⁣o th⁣e answ⁣er:",
  "lmao",
  "lm ao",
  "zoo\\.m",
  "h0t girls",
  "file host",
  "file hosting",
  "here's link",
  "bit\\.[tex]^{}[/tex]ly/3gVQKw3",
  "3gVQKw3",
  "filebit",
  "ly/3gVQKw3",
  "ly/3g",
  "herebit\\.",
  "[tex]^{}[/tex]",
  "I uploaded the answer to",
  "answer:bit\\.",
  "Link Below! bit\\.[tex]^{}[/tex]ly/",
  "prettygirls\\.website",
  "prettygirls website",
  "Photos of me getting fu!c!ke!d in the toilet at school watch here for free - : ₚᵣₑₜₜygᵢᵣₗₛ\\.wₑbₛᵢₜₑ",
  "fu!c!ke!d",
  "ₚᵣₑₜₜygᵢᵣₗₛ\\.wₑbₛᵢₜₑ",
  "Jaiminy`creation myshopify customer care number,9832336299®®®#",
  "jaiminy`creation myshopify customer care number,9832336299®®®#​`",
  "myshopify",
  "ꜱʜᴇ`ꜱ ɴᴜᴅᴇ ᴘʜᴏᴛᴏꜱ ᴀɴᴅ ᴠɪᴅꜱ ʜᴇʀᴇ ᴄᴏᴘʏ ᴛʜᴀᴛ ʟɪɴᴋ ᴀɴᴅ ᴏᴘᴇɴ ɪɴ ᴀ ɴᴇᴡ ᴛᴀʙ - ᵖʳᵉᵗᵗʸᵍⁱʳˡˢ\\.ʷᵉᵇˢⁱᵗᵉ",
  "prettygirls\",website",
  "ꜱʜᴇ`ꜱ ɴᴜᴅᴇ ᴘʜᴏᴛᴏꜱ ᴀɴᴅ ᴠɪᴅꜱ ʜᴇʀᴇ ᴄᴏᴘʏ ᴛʜᴀᴛ ʟɪɴᴋ ᴀɴᴅ ᴏᴘᴇɴ ɪɴ ᴀ ɴᴇᴡ ᴛᴀʙ - ᵖʳᵉᵗᵗʸᵍⁱʳˡˢ\\.ʷᵉᵇˢⁱᵗᵉ`",
  "z\\.oo\\.m",
  "MY ɴᴜᴅᴇ ᴘʜᴏᴛᴏꜱ ᴀɴᴅ ᴠɪᴅꜱ ʜᴇʀᴇ ᴄᴏᴘʏ ᴛʜᴀᴛ ʟɪɴᴋ ᴀɴᴅ ᴏᴘᴇɴ ɪɴ ᴀ ɴᴇᴡ ᴛᴀʙ : ᵖʳᵉᵗᵗʸᵍⁱʳˡˢ\\.ʷᵉᵇˢⁱᵗᵉ",
  "fock",
  "foch",
  "zo om",
  "zo*om",
  "z\\.oom",
  "z oom",
  "z00m",
  "bítch",
  "Gauthmath",
  "msngr",
  "2X07dra",
  "i⁣s [tex]^{}[/tex]in the fil[tex]^{}[/tex]e below",
  "bit[tex]^{}[/tex]\\.ly",
  "f(uck) sh!*t f\\.*ck",
  "jo in",
  "deez",
  "meet code",
  "meeting id",
  "gmeet",
  "Mee\\.tin\\.g I\\.D",
  "bit\\\\.\\[tex\\]\\^\\{\\}\\[\tex\\]ly",
  "fu!ck!ed",
  "www\\.nowdate\\.fun",
  "pu\\*\\*y",
  "ᵂᵃⁱᵗⁱⁿᵍ",
  "ᴄｏᴍᴇ２ᴍᴇ",
  "ᵐʸ",
  "ｂｒａｉｎｌｙ\\.ｔｏｄａｙ",
  "ｗａｈｔ",
  "ｋｎｏｗ",
  "ｄｏ",
  "ʷᵉᵇᶜᵃᵐ",
  "ⁿᵃᵏᵉᵈ",
  "ˢᵖᵃᶜᵉ",
  "ᵇʳᵃⁱⁿˡʸᶜᵒᵐ",
  "ᴵᶠ",
  "ˢᵉᵉ",
  "ʷᵃⁿᵗ",
  "ᴰᵒ",
  "ᵇᵒᵒᵇˢ",
  "ᶠᵒʳ",
  "peynicumrei1985",
  "ᵘˢᵉ",
  "wealthtertentkin1981",
  "ʸᵒᵘʳ",
  "ʷᵒʳʳʸ",
  "ᴰᵒⁿᵗ",
  "ᶠʳᵉᵉ",
  "ⁱᵗˢ",
  "ʷⁱᵗʰ",
  "ᵐᵃˢᵗᵘʳᵇᵃᵗᵉ",
  "ᴵ",
  "suicidal",
  "ˢᵉˣʸᵖʰᵒᵗᵒˢ",
  "ʸᵒᵘ",
  "chatt",
  "ᵒⁿˡⁱⁿᵉ",
  "ᵃ",
  "privovediz1985",
  "ｆｏｒ",
  "ｙｏｕ",
  "ᵍⁱʳˡ",
  "abofimov1986",
  "ʳᵉᵃˡˡʸ",
  "ᵈⁱᶜᵏ",
  "ᵐᵒᵘᵗʰ",
  "ᵇᵃᵈ",
  "s-tupid",
  "ᴾᵘⁿⁱˢʰ",
  "ʷᵃˢ",
  "ⁱⁿ",
  "ᴵᵐ",
  "henquismarim1980",
  "ᵐᵉ",
  "sex-today",
  "ᵒⁿ",
  "ｈｅｒｅ",
  "di\\.ck",
  "ᵇʳᵃⁱⁿˡʸ\\.ᵗᵒᵈᵃʸ",
  "look!",
  "mmmmm",
  "ｔｏ",
  "s\\*x",
  "bit-ch",
  "a-s-s",
  "senpai",
  "masturbating",
  "n-i-g-g-e-r",
  "ˡⁱⁿᵏ",
  "swat",
  "a//ss",
  "ᶠⁱⁿᵈ",
  "ʰᵉʳᵉ",
  "fu\\*cking",
  "dadyy",
  "a/ss",
  "thorght",
  "afro",
  "duk",
  "sex",
  "ⓦⓐⓝⓣ",
  "gayyyy",
  "ｇｏ",
  "ⓨⓞⓤ",
  "virgin",
  "shid",
  "ａｎｄ",
  "ｔｈｅ",
  "ⓢⓔⓔ",
  "d\\*ck",
  "busty",
  "milf",
  "shlt",
  "ⓝⓐⓚⓔⓓ",
  "as\\.s",
  "fu-ck",
  "cn",
  "virginity",
  "fu\\.cking",
  "msg",
  "ƒuçk",
  "sucked!",
  "fucing",
  "j0in",
  "fu\\*ck",
  "someb!ody",
  "drunk",
  "#ERROR!",
  "naked",
  "a/s/s",
  "babes",
  "sexx",
  "peen",
  "fu\\.ck\\.ing",
  "h\\.o\\.e",
  "stu\\*pid",
  "asss",
  "a\\.ss",
  "åšš",
  "ⓜⓔ",
  "niger",
  "aroused",
  "penis",
  "bit\\.ch",
  "f\\*\\*",
  "f#ck",
  "pull-out",
  "i\",m",
  "p\\*\\*\\*\\*",
  "sucked",
  "cuhh",
  "n\\.ggas",
  "glock",
  "pusi",
  "me!?!",
  "bi-tch",
  "sh-it",
  "\\(shut",
  "☺",
  "flirt",
  "obb-ovjk-adtjoin",
  "penes",
  "a\\*s",
  "ni-gga",
  "guidelines",
  "panty",
  "panties",
  "smexy",
  "fūcking",
  "nggaz",
  "di-ck",
  "fu\\.\\.ck",
  "b\\*\\*ch",
  "niggas",
  "whooped",
  "fu\\.cked",
  "b-i-t-c-h",
  "masturbate",
  "dicks",
  "shi\\.t",
  "ngga",
  "homie",
  "juicy",
  "g00gle",
  "assss",
  "p\\*\\*\\*",
  "luv",
  "ಥ_ಥ",
  "boutta",
  "(yeah)",
  "ayy",
  "hiii",
  "sh\\.it",
  "ᵇᵉ",
  "junkie\\.\\.\\.\\.\\.me",
  "ｉｔ",
  "lookin'",
  "shorty",
  "pad\\.let",
  "a\\*\\*",
  "seks!-!ch!at",
  "homophobes",
  "a\\.s\\.s",
  "karens",
  "actin'",
  "butthole",
  "f\\*",
  "keyonn",
  "cha\\.t",
  "ᵃⁿᵈ",
  "bick",
  "as\\.f",
  "ᵗʰᵉ",
  "fkn",
  "bullsh*t",
  "mtf",
  "n\\.gga",
  "thicc",
  "ʷᵒⁿᵗ",
  "ˢᵒʳʳʸ",
  "ᶠᵒˡˡᵒʷ",
  "ᵒⁿˡʸ",
  "ᵀᵒᵖ",
  "ˢⁱᵗᵉ",
  "ᵇᵘʳⁿʸ",
  "ᵗʰⁱˢ",
  "ᶜʰⁱᶜᵏˢ",
  "ᵇᵘˢᵗʸ",
  "\\*\\*\\*\\*",
  "masturbation",
  "peepee",
  "yuh",
  "fk",
  "keyonnn",
  "echo2155",
  "europa2433",
  "lemme",
  "trynna",
  "shawty",
  "shii",
  "finna",
  "tryna",
  "wanna",
  "An y g irl",
  "s ex and",
  "like s ex",
  "wan t to do",
  "twitter",
  "Inst'agram",
  "Snapch'at",
  "Hey Friend",
  "❤",
  "(◍•ᴗ•◍)",
  "looking for friends",
  "looking for some friends",
  "my user is",
  "my username is",
  "An y g ir",
  "g ir l",
  "l ike sx",
  "w an t to do",
  "wh o l ike",
  "Heyy guys",
  "anyone want to be my",
  "Any girl",
  "on snap",
  "snap me",
  "Annnyy",
  "girlllllll",
  "wannt",
  "dirrrtttyyy",
  "chttttt",
  "z oo omm​",
  "dirty chat",
  "ta\\.\\.lk",
  "he\\.\\.lla",
  "bo\\*red​",
  "gírl",
  "Mastûrbate",
  "are you a girl",
  "are you a boy",
  "r u a girl",
  "r u a boy",
  "are u a girl",
  "are u a boy",
  "r you a girl",
  "r you a boy",
  "gí4l",
  "Mastûrbaté",
  "Here's li[tex]^{}[/tex]nk",
  "cutt[tex]^{}[/tex]\\.ly",
  "4Rq[tex]^{}[/tex]tIvk",
  "cutt[tex]^{}[/tex]",
  "cutt",
  "Explanation is[tex]^{}[/tex]",
  "[tex]^{}[/tex] in a file",
  "You can down[tex]^{}[/tex]load",
  "down[tex]^{}[/tex]load",
  "load the answer",
  "Li[tex]^{}[/tex]nk below!",
  "Here's li[tex]^{}[/tex]nk",
  "li[tex]^{}[/tex]nk",
  "b-ored",
  "Timed Test",
  "Ra\\.te me ig bc im bo\\.red",
  "Ra\\.te me",
  "im bo\\.red",
  "Hey Anyone wann\\.a be friends",
  "❁◕ ‿ ◕❁",
  "love u",
  "join for talk​",
  "plz join",
  "Anyone here is on?",
  "Want to have someone to talk to",
  "sugar daddy",
  "sugar baby",
  "sugar mommy",
  "sugar mama",
  "trump 2020",
  "(╥﹏╥)",
  "plz",
  "just want to text",
  "can i give you my #",
  "can i give u my #",
  "can i get ur #",
  "can i get your #",
  "can you give me your #",
  "can u give me your #",
  "can u give me ur #",
  "can you give me ur #",
  "can you share your #",
  "can u share your #",
  "can u share ur #",
  "can you share ur #",
  "can i get ur #",
  "can i get your #",
  "\\^{}",
  "\\bbit\\.ly\\b",
  "\\bmdaf",
  "\\bfuck\\b",
  "fuck",
  "\\bc\\.k\\.",
  "fvch",
  "$:€X",
  "\\bsex",
  "Pls dont report",
  "Anyone need a friend or someone to talk to?",
  "Anyone need a friend or someone to talk to",
  "Anyone need a friend"
];

export default profList.map(item => {
  return new RegExp(item);
});